export const cardList = [
    {
      id:1,
      status: "Без статуса",
      theme: "Web design",
      ThemeColor: "_orange",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:2,
      status: "Без статуса",
      theme: "Research",
      ThemeColor: "_green",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:3,
      status: "Без статуса",
      theme: "Web design",
      ThemeColor: "_orange",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:4,
      status: "Без статуса",
      theme: "Copywriting",
      ThemeColor: "_purple",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:5,
      status: "Без статуса",
      theme: "Web design",
      ThemeColor: "_orange",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:6,
      status: "Нужно сделать",
      theme: "Research",
      ThemeColor: "_green",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:7,
      status: "В работе",
      theme: "Copywriting",
      ThemeColor: "_purple",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:8,
      status: "В работе",
      theme: "Copywriting",
      ThemeColor: "_purple",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:9,
      status: "В работе",
      theme: "Web design",
      ThemeColor: "_orange",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:10,
      status: "Тестирование",
      theme: "Research",
      ThemeColor: "_green",
      title: "Новая задача",
      date: "30.10.23",
    },
    {
      id:11,
      status: "Готово",
      theme: "Research",
      ThemeColor: "_green",
      title: "Новая задача",
      date: "30.10.23",
    },
  ];